[build]
  functions = "functions"  # This should match the directory name where your server.js is located

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true  # This ensures that the specified redirect overrides less specific rules
